name: logcraft
description: A flexible, cross-platform logging solution for Dart and Flutter applications with async operations and environment-based configuration.
version: 1.0.1
homepage: https://github.com/changyy/logcraft_dart
repository: https://github.com/changyy/logcraft_dart
issue_tracker: https://github.com/changyy/logcraft_dart/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0
  mockito: ^5.4.0
